### ISSUE TITLE
error on creating environment with conda_env.txt

### ISSUE THREAD

**Issue by ecwheele** [YeoLab/rbp-maps#5]
command:
conda env create -f conda_env.txt -n rbp-maps2

output:
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...................

ResolvePackageNotFound: 
  - statsmodels 0.8.0 np110py27_0

**Comment by byee4** [comment]
Updated the requirements, please see:

[https://github.com/YeoLab/rbp-maps/blob/master/create_environment_rbp-maps.sh](url)
