### ISSUE TITLE
Coordinate files

### ISSUE THREAD

**Issue by mstrazar** [YeoLab/rbp-maps#6]
Dear authors, thank you for this valuable resource!

Are the coordinates in files 
examples/data/positive.a3ss.txt
examples/data/positive.a5ss.txt
examples/data/positive.mxe.txt
examples/data/positive.ri.txt
examples/data/positive.se.txt

mapped to the hg38 genome? It would make sense to mention this somewhere for future.

Kind regards,
Martin

**Comment by byee4** [comment]
Hi Martin, you're right. The files I used are based on hg19 assembly. Also I've added a section containing a link to directly download all rMATS files (based on hg19 assembly), here is the link: [rMATS](https://s3-us-west-1.amazonaws.com/external-collaborator-data/rbp-maps-PMID30413564/rMATS_jxc_files.tar.gz)

**Comment by mstrazar** [comment]
Thank you, much appreciated!
